version: '3'

services:
  jekyll:
    image: jekyll/jekyll
    container_name: modern-resume-theme
    command: jekyll serve --livereload
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - ./:/srv/jekyll
